[project]
name = "intropythonprogramming"
version = "0.1.0"
requires-python = ">=3.12.7"
dependencies = [
    "ipykernel>=6.29.5",
    "ipympl>=0.9.7",
    "matplotlib>=3.10.1",
    "nbconvert>=7.16.6",
    "numpy>=2.2.4",
    "otter-grader>=6.1.2",
    "scipy>=1.15.2",
]
